modLoader="javafml"
loaderVersion="[2,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/Autovw/AdvancedNetherite/issues"

[[mods]]
modId="advancednetherite"
version="${mod_version}"
displayName="Advanced Netherite"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/master/advancednetherite/update.json"
displayURL="https://github.com/Autovw/AdvancedNetherite/wiki"
logoFile="advancednetherite_banner.png"
#credits=""
authors="Autovw"
description='''
A vanilla and add-on friendly, open-source mod that adds in more tiers of Netherite! The goal of the mod is to extend the vanilla Minecraft experience by adding more goals to achieve.
Visit the GitHub Wiki for more information on everything this mod adds.
'''

[[dependencies.advancednetherite]]
    modId="neoforge"
    # The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # 'required' requires the mod to exist, 'optional' does not
    # 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
    type="required"
    versionRange="[21.10.0-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advancednetherite]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.10]"
    ordering="NONE"
    side="BOTH"

[modproperties.advancednetherite]
    #Catalogue also supports items. Use "catalogueItemIcon" instead.
    catalogueImageIcon="advancednetherite_logo.png" #Optional support for Cataloque mod.
    configuredBackground="minecraft:textures/block/netherite_block.png" #Optional support for Configured mod.

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.advancednetherite]
#openGLVersion="[3.2,)"
